# Header Menu
menu:
  Home: /
  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Featured Note
feature_note_title: 'Using Ansible to Deploy Python Applications'
feature_note_date: 'April 18th, 2016'
feature_note_author: 'Max Fowler'
feature_note_path: "2016/04/18/flask-ansible/"
feature_note_excerpt: 'My new favorite tool is an Ansible template to quickly deploy a new Flask app to
Amazon Web Services.  It logs error messages to slack, has database
connectivity, and is fully idempotent — no need to remember server state. I find it very useful for getting small applications up and running quickly.
It is also useful for starting a new project to know from the onset that
deployment is already taken care of so I can focus on the actual project.'

# Featured Case Study
feature_case_title: 'Verdes Pinpoints'
feature_case_date: 'June 14th, 2016'
feature_case_author: 'Patrick Steadman'
feature_case_path: '2016/06/14/Pinpoints/'
feature_case_project_path: 'http://pinpoints.io'
feature_case_lede: 'We built an interactive 3D landing page for a marketing data visualization tool.'
feature_case_excerpt: 'The engineers who built ReactJS were inspired by the efficiency 
and simplicity of the “DOOM” video game engine, 
so it’s not surprising that React is a good tool for building responsive 3D websites. 
The PinPoints build convinced us that React’s declarative components are a great fit 
for developing 3D user interfaces in the browser.'

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/ptsteadman
  twitter: https://twitter.com/ptsteadman
  facebook: https://www.facebook.com/ptsteadman
  rss: atom.xml
  linkedin: https://linkedin.com/in/ptsteadman
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: computerlab_ # twitter username without the @
default_author: Anonymous

about: Computer Lab is a software development and marketing company based in Brooklyn, New York. <br><br> Computer Lab was founded in 2015, and is focused on so on and so forth.
phone: 716-472-4484
email: hi@computerlab.io
address_1: 140 Metropolitan Ave.
address_2: 5th Floor
address_3: Brooklyn, NY 11249
skype: ptsteadman
lat: 40.715911 
long: -73.962147
